name: Refresh Profile Quote

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

# On définit la variable globale pour utiliser Node 24 sur tout le workflow
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  refresh-quote:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Version v5 mise à jour
    - name: Checkout repository
      uses: actions/checkout@v5

    # 2. Version v6 mise à jour
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    # 3. Lancer le script qui change la citation
    - name: Run quote script
      run: python update_quote.py

    # 4. Enregistrer les modifications et les envoyer sur GitHub
    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "bot: nouvelle citation de dev" || exit 0
        git push
